name: CMake

on: [push]

jobs:
  CodeCoverageReport:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install ninja toolchain
      run: sudo apt-get install -y ninja-build

    - name: Install lcov
      run: sudo apt-get install -y lcov

    - name: Install google test
      run: sudo apt-get install -y libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

    - name: Build & test
      working-directory: ${{github.workspace}}
      shell: bash
      env:
       CC:   gcc-10
       CXX:  g++-10
      run: make run_coverage

    - name: Upload coverage
      working-directory: ${{github.workspace}}
      shell: bash
      run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Error while collecting coverage reports"
