name: CMake

on: [push]

jobs:
  CodeCoverageReport:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get install -y ninja-build lcov libgtest-dev

    - name: Build & test
      working-directory: ${{github.workspace}}
      shell: bash
      run: make run_coverage

    - name: Upload coverage
      working-directory: ${{github.workspace}}
      shell: bash
      run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Error while collecting coverage reports"
