name: Windows Build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  Build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Prepare build
      working-directory: ${{github.workspace}}
      run:
        cmake -E make_directory ${{github.workspace}}/Build

    - name: Run toolchain
      working-directory: ${{github.workspace}}/Build
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/Build
      run: |
        cmake --build . --config $BUILD_TYPE
